server:
  port: 8086
  servlet:
    context-path: /test

# 数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LS_ERP_DB?setUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: Ysq13870271456!
    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis的相关配置
mybatis:
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ls.erp.entity
  callSettersOnNulls: true

logging:
  level:
    com.ls.erp: debug
